spring:
  profiles:
    active: local

zuul:
  prefix: '/api'

  routes:
    items-service:
      path: '/items/**'
    authorization-service:
      sensitiveHeaders: Cookie,Set-Cookie
      path: '/oauth/**'
      oauth:
        clientId: 'crmClient1'
        secret: 'crmSuperSecret'